import Head from 'next/head'
import Image from 'next/image'
// import styles from '@components/styles/Home.module.scss'
import largeImage from '@images/large-logo.svg';
import heroImage from '@images/hero__image.png';
import { useEffect, useRef } from 'react';


export default function Home() {
  const largeLogoRef = useRef();
  const heroImageRef = useRef();
  const backgroundRef = useRef();
  useEffect(() => {
    const logo = largeLogoRef.current;
    const hero = heroImageRef.current;
    const bg = backgroundRef.current;

    logo.style.scale="1";
    hero.style.scale=".92";
    setTimeout(function () {
      bg.style.setProperty("--bg-color", "var(--red)")
    }, 150)
    console.log(logo, hero)
  })
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main ref={backgroundRef}>
        <h1 title="Valorant">Valorant</h1>
        <div className="large__logo" ref={largeLogoRef}>
          <Image src={largeImage} alt='asd' />
        </div>
        <div className="hero__image " ref={heroImageRef}>
          <Image src={heroImage} alt='asd' />
        </div>
      </main>
    </>
  )
}
